[project]
name = "inspect-machiavelli"
description = "MACHIAVELLI benchmark implemented as an Inspect AI evaluation"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "asteval>=1.0.8",
    "huggingface-hub>=1.17.0",
    "inspect-ai",
    "pydantic>=2.13.4",
    "torch",
]

[project.optional-dependencies]
hf-models = [
    "accelerate>=1.13.0",
    "transformers>=5.9.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[[tool.uv.index]] # TODO: remove this for the final version
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources] # TODO: remove this for the final version
torch = { index = "pytorch-cu126" }

